name: CD

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: ${{ secrets.DOCKER_USERNAME }}/simple-node-app:latest
        load: true

    - name: Run Truvy vulnerability Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ secrets.DOCKER_USERNAME }}/simple-node-app:latest'
        format: 'table'
        output: 'trivy-report.txt' # out will be saved on a txt file
        exit-code: '1' # if there is an unfixed vulnerability pipeline will be failed.
        ignore-unfixed: true
        vuln-type: 'library'
        severity: 'CRITICAL,HIGH' # failed only for High and Critical vulnerabilities. Medium and Low vulnerabilities will be ignored.

    - name: Upload Trivy Security Report
      if: always() # if scan fali and stopped the pipeline, output will be saved on txt report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-security-report
        path: trivy-report.txt

    - name: Push Docker image
      # if scan pass, this step will be executed
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/simple-node-app:latest